#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDane_firmy(Dane_firmy instance);
    partial void UpdateDane_firmy(Dane_firmy instance);
    partial void DeleteDane_firmy(Dane_firmy instance);
    partial void InsertUzytkownicy(Uzytkownicy instance);
    partial void UpdateUzytkownicy(Uzytkownicy instance);
    partial void DeleteUzytkownicy(Uzytkownicy instance);
    partial void InsertFaktury(Faktury instance);
    partial void UpdateFaktury(Faktury instance);
    partial void DeleteFaktury(Faktury instance);
    partial void InsertKlienci(Klienci instance);
    partial void UpdateKlienci(Klienci instance);
    partial void DeleteKlienci(Klienci instance);
    partial void InsertOpis_faktury(Opis_faktury instance);
    partial void UpdateOpis_faktury(Opis_faktury instance);
    partial void DeleteOpis_faktury(Opis_faktury instance);
    partial void InsertProdukty(Produkty instance);
    partial void UpdateProdukty(Produkty instance);
    partial void DeleteProdukty(Produkty instance);
    partial void InsertUprawnienia(Uprawnienia instance);
    partial void UpdateUprawnienia(Uprawnienia instance);
    partial void DeleteUprawnienia(Uprawnienia instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Warehouse_Management_System.Properties.Settings.Default.DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dane_firmy> Dane_firmy
		{
			get
			{
				return this.GetTable<Dane_firmy>();
			}
		}
		
		public System.Data.Linq.Table<Uzytkownicy> Uzytkownicy
		{
			get
			{
				return this.GetTable<Uzytkownicy>();
			}
		}
		
		public System.Data.Linq.Table<Faktury> Faktury
		{
			get
			{
				return this.GetTable<Faktury>();
			}
		}
		
		public System.Data.Linq.Table<Klienci> Klienci
		{
			get
			{
				return this.GetTable<Klienci>();
			}
		}
		
		public System.Data.Linq.Table<Opis_faktury> Opis_faktury
		{
			get
			{
				return this.GetTable<Opis_faktury>();
			}
		}
		
		public System.Data.Linq.Table<Produkty> Produkty
		{
			get
			{
				return this.GetTable<Produkty>();
			}
		}
		
		public System.Data.Linq.Table<Uprawnienia> Uprawnienia
		{
			get
			{
				return this.GetTable<Uprawnienia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dane_firmy")]
	public partial class Dane_firmy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private string _Ulica;
		
		private string _Nr_budynku;
		
		private string _Nr_mieszkania;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Nip;
		
		private string _Telefon;
		
		private EntitySet<Faktury> _Fakturies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnUlicaChanging(string value);
    partial void OnUlicaChanged();
    partial void OnNr_budynkuChanging(string value);
    partial void OnNr_budynkuChanged();
    partial void OnNr_mieszkaniaChanging(string value);
    partial void OnNr_mieszkaniaChanged();
    partial void OnMiastoChanging(string value);
    partial void OnMiastoChanged();
    partial void OnKod_pocztowyChanging(string value);
    partial void OnKod_pocztowyChanged();
    partial void OnNipChanging(string value);
    partial void OnNipChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Dane_firmy()
		{
			this._Fakturies = new EntitySet<Faktury>(new Action<Faktury>(this.attach_Fakturies), new Action<Faktury>(this.detach_Fakturies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="VarChar(100)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this.OnUlicaChanging(value);
					this.SendPropertyChanging();
					this._Ulica = value;
					this.SendPropertyChanged("Ulica");
					this.OnUlicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_budynku", DbType="VarChar(10)")]
		public string Nr_budynku
		{
			get
			{
				return this._Nr_budynku;
			}
			set
			{
				if ((this._Nr_budynku != value))
				{
					this.OnNr_budynkuChanging(value);
					this.SendPropertyChanging();
					this._Nr_budynku = value;
					this.SendPropertyChanged("Nr_budynku");
					this.OnNr_budynkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_mieszkania", DbType="VarChar(10)")]
		public string Nr_mieszkania
		{
			get
			{
				return this._Nr_mieszkania;
			}
			set
			{
				if ((this._Nr_mieszkania != value))
				{
					this.OnNr_mieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._Nr_mieszkania = value;
					this.SendPropertyChanged("Nr_mieszkania");
					this.OnNr_mieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this.OnMiastoChanging(value);
					this.SendPropertyChanging();
					this._Miasto = value;
					this.SendPropertyChanged("Miasto");
					this.OnMiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this.OnKod_pocztowyChanging(value);
					this.SendPropertyChanging();
					this._Kod_pocztowy = value;
					this.SendPropertyChanged("Kod_pocztowy");
					this.OnKod_pocztowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="VarChar(20)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this.OnNipChanging(value);
					this.SendPropertyChanging();
					this._Nip = value;
					this.SendPropertyChanged("Nip");
					this.OnNipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dane_firmy_Faktury", Storage="_Fakturies", ThisKey="Id", OtherKey="Id_naszej_firmy")]
		public EntitySet<Faktury> Fakturies
		{
			get
			{
				return this._Fakturies;
			}
			set
			{
				this._Fakturies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fakturies(Faktury entity)
		{
			this.SendPropertyChanging();
			entity.Dane_firmy = this;
		}
		
		private void detach_Fakturies(Faktury entity)
		{
			this.SendPropertyChanging();
			entity.Dane_firmy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzytkownicy")]
	public partial class Uzytkownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _Login;
		
		private string _Haslo;
		
		private int _Uprawnienie;
		
		private EntityRef<Uprawnienia> _Uprawnienia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnHasloChanging(string value);
    partial void OnHasloChanged();
    partial void OnUprawnienieChanging(int value);
    partial void OnUprawnienieChanged();
    #endregion
		
		public Uzytkownicy()
		{
			this._Uprawnienia = default(EntityRef<Uprawnienia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haslo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Haslo
		{
			get
			{
				return this._Haslo;
			}
			set
			{
				if ((this._Haslo != value))
				{
					this.OnHasloChanging(value);
					this.SendPropertyChanging();
					this._Haslo = value;
					this.SendPropertyChanged("Haslo");
					this.OnHasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uprawnienie", DbType="Int NOT NULL")]
		public int Uprawnienie
		{
			get
			{
				return this._Uprawnienie;
			}
			set
			{
				if ((this._Uprawnienie != value))
				{
					if (this._Uprawnienia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUprawnienieChanging(value);
					this.SendPropertyChanging();
					this._Uprawnienie = value;
					this.SendPropertyChanged("Uprawnienie");
					this.OnUprawnienieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uprawnienia_Uzytkownicy", Storage="_Uprawnienia", ThisKey="Uprawnienie", OtherKey="Id", IsForeignKey=true)]
		public Uprawnienia Uprawnienia
		{
			get
			{
				return this._Uprawnienia.Entity;
			}
			set
			{
				Uprawnienia previousValue = this._Uprawnienia.Entity;
				if (((previousValue != value) 
							|| (this._Uprawnienia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uprawnienia.Entity = null;
						previousValue.Uzytkownicies.Remove(this);
					}
					this._Uprawnienia.Entity = value;
					if ((value != null))
					{
						value.Uzytkownicies.Add(this);
						this._Uprawnienie = value.Id;
					}
					else
					{
						this._Uprawnienie = default(int);
					}
					this.SendPropertyChanged("Uprawnienia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faktury")]
	public partial class Faktury : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_klienta;
		
		private int _Id_naszej_firmy;
		
		private string _Nr_faktury;
		
		private System.DateTime _Data_wystawienia;
		
		private EntitySet<Opis_faktury> _Opis_fakturies;
		
		private EntityRef<Dane_firmy> _Dane_firmy;
		
		private EntityRef<Klienci> _Klienci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_klientaChanging(int value);
    partial void OnId_klientaChanged();
    partial void OnId_naszej_firmyChanging(int value);
    partial void OnId_naszej_firmyChanged();
    partial void OnNr_fakturyChanging(string value);
    partial void OnNr_fakturyChanged();
    partial void OnData_wystawieniaChanging(System.DateTime value);
    partial void OnData_wystawieniaChanged();
    #endregion
		
		public Faktury()
		{
			this._Opis_fakturies = new EntitySet<Opis_faktury>(new Action<Opis_faktury>(this.attach_Opis_fakturies), new Action<Opis_faktury>(this.detach_Opis_fakturies));
			this._Dane_firmy = default(EntityRef<Dane_firmy>);
			this._Klienci = default(EntityRef<Klienci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_klienta", DbType="Int NOT NULL")]
		public int Id_klienta
		{
			get
			{
				return this._Id_klienta;
			}
			set
			{
				if ((this._Id_klienta != value))
				{
					if (this._Klienci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_klientaChanging(value);
					this.SendPropertyChanging();
					this._Id_klienta = value;
					this.SendPropertyChanged("Id_klienta");
					this.OnId_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_naszej_firmy", DbType="Int NOT NULL")]
		public int Id_naszej_firmy
		{
			get
			{
				return this._Id_naszej_firmy;
			}
			set
			{
				if ((this._Id_naszej_firmy != value))
				{
					if (this._Dane_firmy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_naszej_firmyChanging(value);
					this.SendPropertyChanging();
					this._Id_naszej_firmy = value;
					this.SendPropertyChanged("Id_naszej_firmy");
					this.OnId_naszej_firmyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_faktury", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nr_faktury
		{
			get
			{
				return this._Nr_faktury;
			}
			set
			{
				if ((this._Nr_faktury != value))
				{
					this.OnNr_fakturyChanging(value);
					this.SendPropertyChanging();
					this._Nr_faktury = value;
					this.SendPropertyChanged("Nr_faktury");
					this.OnNr_fakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_wystawienia", DbType="Date NOT NULL")]
		public System.DateTime Data_wystawienia
		{
			get
			{
				return this._Data_wystawienia;
			}
			set
			{
				if ((this._Data_wystawienia != value))
				{
					this.OnData_wystawieniaChanging(value);
					this.SendPropertyChanging();
					this._Data_wystawienia = value;
					this.SendPropertyChanged("Data_wystawienia");
					this.OnData_wystawieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktury_Opis_faktury", Storage="_Opis_fakturies", ThisKey="Id", OtherKey="Id_faktury")]
		public EntitySet<Opis_faktury> Opis_fakturies
		{
			get
			{
				return this._Opis_fakturies;
			}
			set
			{
				this._Opis_fakturies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dane_firmy_Faktury", Storage="_Dane_firmy", ThisKey="Id_naszej_firmy", OtherKey="Id", IsForeignKey=true)]
		public Dane_firmy Dane_firmy
		{
			get
			{
				return this._Dane_firmy.Entity;
			}
			set
			{
				Dane_firmy previousValue = this._Dane_firmy.Entity;
				if (((previousValue != value) 
							|| (this._Dane_firmy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dane_firmy.Entity = null;
						previousValue.Fakturies.Remove(this);
					}
					this._Dane_firmy.Entity = value;
					if ((value != null))
					{
						value.Fakturies.Add(this);
						this._Id_naszej_firmy = value.Id;
					}
					else
					{
						this._Id_naszej_firmy = default(int);
					}
					this.SendPropertyChanged("Dane_firmy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Faktury", Storage="_Klienci", ThisKey="Id_klienta", OtherKey="Id", IsForeignKey=true)]
		public Klienci Klienci
		{
			get
			{
				return this._Klienci.Entity;
			}
			set
			{
				Klienci previousValue = this._Klienci.Entity;
				if (((previousValue != value) 
							|| (this._Klienci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klienci.Entity = null;
						previousValue.Fakturies.Remove(this);
					}
					this._Klienci.Entity = value;
					if ((value != null))
					{
						value.Fakturies.Add(this);
						this._Id_klienta = value.Id;
					}
					else
					{
						this._Id_klienta = default(int);
					}
					this.SendPropertyChanged("Klienci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opis_fakturies(Opis_faktury entity)
		{
			this.SendPropertyChanging();
			entity.Faktury = this;
		}
		
		private void detach_Opis_fakturies(Opis_faktury entity)
		{
			this.SendPropertyChanging();
			entity.Faktury = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klienci")]
	public partial class Klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private string _Ulica;
		
		private string _Nr_budynku;
		
		private string _Nr_mieszkania;
		
		private string _Miasto;
		
		private string _Kod_pocztowy;
		
		private string _Nip;
		
		private string _Telefon;
		
		private EntitySet<Faktury> _Fakturies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnUlicaChanging(string value);
    partial void OnUlicaChanged();
    partial void OnNr_budynkuChanging(string value);
    partial void OnNr_budynkuChanged();
    partial void OnNr_mieszkaniaChanging(string value);
    partial void OnNr_mieszkaniaChanged();
    partial void OnMiastoChanging(string value);
    partial void OnMiastoChanged();
    partial void OnKod_pocztowyChanging(string value);
    partial void OnKod_pocztowyChanged();
    partial void OnNipChanging(string value);
    partial void OnNipChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Klienci()
		{
			this._Fakturies = new EntitySet<Faktury>(new Action<Faktury>(this.attach_Fakturies), new Action<Faktury>(this.detach_Fakturies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="VarChar(100)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this.OnUlicaChanging(value);
					this.SendPropertyChanging();
					this._Ulica = value;
					this.SendPropertyChanged("Ulica");
					this.OnUlicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_budynku", DbType="VarChar(10)")]
		public string Nr_budynku
		{
			get
			{
				return this._Nr_budynku;
			}
			set
			{
				if ((this._Nr_budynku != value))
				{
					this.OnNr_budynkuChanging(value);
					this.SendPropertyChanging();
					this._Nr_budynku = value;
					this.SendPropertyChanged("Nr_budynku");
					this.OnNr_budynkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_mieszkania", DbType="VarChar(10)")]
		public string Nr_mieszkania
		{
			get
			{
				return this._Nr_mieszkania;
			}
			set
			{
				if ((this._Nr_mieszkania != value))
				{
					this.OnNr_mieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._Nr_mieszkania = value;
					this.SendPropertyChanged("Nr_mieszkania");
					this.OnNr_mieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miasto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Miasto
		{
			get
			{
				return this._Miasto;
			}
			set
			{
				if ((this._Miasto != value))
				{
					this.OnMiastoChanging(value);
					this.SendPropertyChanging();
					this._Miasto = value;
					this.SendPropertyChanged("Miasto");
					this.OnMiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_pocztowy", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Kod_pocztowy
		{
			get
			{
				return this._Kod_pocztowy;
			}
			set
			{
				if ((this._Kod_pocztowy != value))
				{
					this.OnKod_pocztowyChanging(value);
					this.SendPropertyChanging();
					this._Kod_pocztowy = value;
					this.SendPropertyChanged("Kod_pocztowy");
					this.OnKod_pocztowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nip", DbType="VarChar(20)")]
		public string Nip
		{
			get
			{
				return this._Nip;
			}
			set
			{
				if ((this._Nip != value))
				{
					this.OnNipChanging(value);
					this.SendPropertyChanging();
					this._Nip = value;
					this.SendPropertyChanged("Nip");
					this.OnNipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Faktury", Storage="_Fakturies", ThisKey="Id", OtherKey="Id_klienta")]
		public EntitySet<Faktury> Fakturies
		{
			get
			{
				return this._Fakturies;
			}
			set
			{
				this._Fakturies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fakturies(Faktury entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = this;
		}
		
		private void detach_Fakturies(Faktury entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opis_faktury")]
	public partial class Opis_faktury : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_faktury;
		
		private int _Id_produktu;
		
		private EntityRef<Faktury> _Faktury;
		
		private EntityRef<Produkty> _Produkty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_fakturyChanging(int value);
    partial void OnId_fakturyChanged();
    partial void OnId_produktuChanging(int value);
    partial void OnId_produktuChanged();
    #endregion
		
		public Opis_faktury()
		{
			this._Faktury = default(EntityRef<Faktury>);
			this._Produkty = default(EntityRef<Produkty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_faktury", DbType="Int NOT NULL")]
		public int Id_faktury
		{
			get
			{
				return this._Id_faktury;
			}
			set
			{
				if ((this._Id_faktury != value))
				{
					if (this._Faktury.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_fakturyChanging(value);
					this.SendPropertyChanging();
					this._Id_faktury = value;
					this.SendPropertyChanged("Id_faktury");
					this.OnId_fakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_produktu", DbType="Int NOT NULL")]
		public int Id_produktu
		{
			get
			{
				return this._Id_produktu;
			}
			set
			{
				if ((this._Id_produktu != value))
				{
					if (this._Produkty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_produktuChanging(value);
					this.SendPropertyChanging();
					this._Id_produktu = value;
					this.SendPropertyChanged("Id_produktu");
					this.OnId_produktuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktury_Opis_faktury", Storage="_Faktury", ThisKey="Id_faktury", OtherKey="Id", IsForeignKey=true)]
		public Faktury Faktury
		{
			get
			{
				return this._Faktury.Entity;
			}
			set
			{
				Faktury previousValue = this._Faktury.Entity;
				if (((previousValue != value) 
							|| (this._Faktury.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Faktury.Entity = null;
						previousValue.Opis_fakturies.Remove(this);
					}
					this._Faktury.Entity = value;
					if ((value != null))
					{
						value.Opis_fakturies.Add(this);
						this._Id_faktury = value.Id;
					}
					else
					{
						this._Id_faktury = default(int);
					}
					this.SendPropertyChanged("Faktury");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkty_Opis_faktury", Storage="_Produkty", ThisKey="Id_produktu", OtherKey="Id", IsForeignKey=true)]
		public Produkty Produkty
		{
			get
			{
				return this._Produkty.Entity;
			}
			set
			{
				Produkty previousValue = this._Produkty.Entity;
				if (((previousValue != value) 
							|| (this._Produkty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produkty.Entity = null;
						previousValue.Opis_fakturies.Remove(this);
					}
					this._Produkty.Entity = value;
					if ((value != null))
					{
						value.Opis_fakturies.Add(this);
						this._Id_produktu = value.Id;
					}
					else
					{
						this._Id_produktu = default(int);
					}
					this.SendPropertyChanged("Produkty");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkty")]
	public partial class Produkty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private string _Opis;
		
		private decimal _Cena_netto;
		
		private int _Vat;
		
		private EntitySet<Opis_faktury> _Opis_fakturies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnCena_nettoChanging(decimal value);
    partial void OnCena_nettoChanged();
    partial void OnVatChanging(int value);
    partial void OnVatChanged();
    #endregion
		
		public Produkty()
		{
			this._Opis_fakturies = new EntitySet<Opis_faktury>(new Action<Opis_faktury>(this.attach_Opis_fakturies), new Action<Opis_faktury>(this.detach_Opis_fakturies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena_netto", DbType="Money NOT NULL")]
		public decimal Cena_netto
		{
			get
			{
				return this._Cena_netto;
			}
			set
			{
				if ((this._Cena_netto != value))
				{
					this.OnCena_nettoChanging(value);
					this.SendPropertyChanging();
					this._Cena_netto = value;
					this.SendPropertyChanged("Cena_netto");
					this.OnCena_nettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vat", DbType="Int NOT NULL")]
		public int Vat
		{
			get
			{
				return this._Vat;
			}
			set
			{
				if ((this._Vat != value))
				{
					this.OnVatChanging(value);
					this.SendPropertyChanging();
					this._Vat = value;
					this.SendPropertyChanged("Vat");
					this.OnVatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkty_Opis_faktury", Storage="_Opis_fakturies", ThisKey="Id", OtherKey="Id_produktu")]
		public EntitySet<Opis_faktury> Opis_fakturies
		{
			get
			{
				return this._Opis_fakturies;
			}
			set
			{
				this._Opis_fakturies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opis_fakturies(Opis_faktury entity)
		{
			this.SendPropertyChanging();
			entity.Produkty = this;
		}
		
		private void detach_Opis_fakturies(Opis_faktury entity)
		{
			this.SendPropertyChanging();
			entity.Produkty = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uprawnienia")]
	public partial class Uprawnienia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<Uzytkownicy> _Uzytkownicies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Uprawnienia()
		{
			this._Uzytkownicies = new EntitySet<Uzytkownicy>(new Action<Uzytkownicy>(this.attach_Uzytkownicies), new Action<Uzytkownicy>(this.detach_Uzytkownicies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uprawnienia_Uzytkownicy", Storage="_Uzytkownicies", ThisKey="Id", OtherKey="Uprawnienie")]
		public EntitySet<Uzytkownicy> Uzytkownicies
		{
			get
			{
				return this._Uzytkownicies;
			}
			set
			{
				this._Uzytkownicies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uzytkownicies(Uzytkownicy entity)
		{
			this.SendPropertyChanging();
			entity.Uprawnienia = this;
		}
		
		private void detach_Uzytkownicies(Uzytkownicy entity)
		{
			this.SendPropertyChanging();
			entity.Uprawnienia = null;
		}
	}
}
#pragma warning restore 1591
